
export default function About() {
  return (
    <div className="flex flex-col w-full px-6 pt-12 mb-10 pr-10">
        <h1 className="flex justify-center text-blue-900 text-2xl font-serif font-bold my-2">Laz and the Commenhater</h1>
        <hr className="border-t-2 border-yellow-300 mx-10 my-5"/>
        <br/>
        <div className="mr-28 md:mr-14 sm:mr-0">
            <h2 className="text-xl font-bold text-blue-900 underline underline-offset-8">Who am I and what is this blog about?</h2>
            <h3 className="text-lg font-bold mt-2 py-2 text-yellow-500 underline">Short Version</h3>
            <p className="indent-10">My name is Laz Austin, the creator and primary contributor for the commenhater. I am a software developer from Jackson, Mississippi in the US. I am also a huge nerd who loves sci-fi (space operas mostly), superheroes, foreign languages (I’m multilingual) and culture, history (especially military), crazy genres of music (symphonic power metal anyone?), libertarian philosophy, playing the piano, martial arts, tending bar, cooking, reading, and of course my beautiful wife, Cathy. <p className="indent-10">Currently, this blog is an “everything bagel” of sorts. I may eventually split it into two or more focusing on specific subjects. But for now, I would like to write about tech issues and trends, political commentary from a libertarian perspective, non-fiction book reviews and how their theses challenge or contribute to libertarian thought and activism, Movies/TV reviews with a focus on the industry’s recent erosion by radical wokeism, song/album/band reviews focusing on my eccentric tastes which are rarely covered in the US, men’s lifestyle strategies and topics, and the occasional miscellaneous subject.</p><p>Lastly, if you don't have a sense of humor, it should be noted this is not a "hate" blog so to speak, nor am I a white supremacist or something crazy. In part, it is a reaction to a radical woke movement wherein it's become popular to label or shout down anyone who disagrees with their agenda, points out any nuance, or has any kind of independent opinion as hateful, whether it be racist, mysoginistic, homophobic, or whatever. More often than not in their eyes, I am one or all of the isms and phobes out there by default because of my specific gender, race, and sexuality. If that's going to be the case, why not just own it?</p></p>
            <h3 className="text-lg font-bold mt-2 py-2 text-yellow-500 underline underline-offset-4">Long Version</h3>
            <p className="">
              <p>I’ve always loved to write and been passionate about several subjects. It probably all started in middle school when I wrote a story about a large monster I called “Freakazoid” attacking our school. The teacher made us read our stories out loud, and to my surprise, the whole class thought mine was hilarious. Around the same time, I started reading voraciously: first with the Animorphs series, Lord of the Rings, and Harry Potter, then later with my dad's military fiction books laying around the house, starting with Dale Brown and moving on to Stephen Coonts, Larry Bond, Tom Clancy, and some Clive Cussler and others in-between. The military fiction books sparked a passion for history and international relations as I was constantly looking up details about the countries, cultures, and militaries of the conflicts involved. 
              </p>
              <p className="indent-10">Later, I wrote sports for a small newsletter in high school amongst my homework (book reviews being my favorite). At the time, I had just earned a 2nd Dan in Tang Soo Do and Associate Instructor certification but I was also exploring mixed martial arts and learning Ninjutsu. My Tang Soo Do instructor was a traditional martial artist who was stubbornly against mixing or learning new styles. Internally, I found myself debating the philosophical merits of the two approaches, culminating in a 20+ page research paper comparing Chuck Norris and Bruce Lee, who sort of represented both sides, for my final English project.
              </p>             
              <p className="indent-10">What do you often get when you cross interests in philosophy and history/international relations…? Politics! My growing interest and strong opinions led to a weekly column called “The Skunk Works” (named after the secretive Lockheed Martin think tank famous for developing the F-22, F-35, SR-71, etc)  in the university newspaper. To be honest, I’m not proud of the opinions I had and the articles I wrote in my early formative years. They were solidly neoconservative, uninformed, and dogmatic, but gradually shifted to libertarianism during the ‘08 election and Ron Paul Revolution. Philosophy and objectivity, an “empty cup” to use Bruce Lee’s phraseology,  had become important to me at this point, so I refused to just “go with the flow” of my upbringing, peer pressure (my home state is hardcore Republican), and the media. 
              </p>
              <p className="indent-10">While looking into ALL the candidates, I was shocked, like many, by the controversy around Ron Paul’s statements about 9/11 and Iraq. By then, I’d mostly shifted my reading to history, military, and politics non-fiction. And everything he said just…jived. After more investigation, I decided to join the Libertarian Party. I formed a county affilliate from scratch, consistently attended city council meetings, organized or participated in community events, campaigned for candidates, recruited new members, served briefly as Vice Chair for the MS Libertarian Party, and more. 
              </p>
              <p className="indent-10">If you haven't figured it out by now, politics is a passion of mine. That means many of the posts on this blog will be dealing with it, including those under seemingly unrelated topics. In a broader sense culturally, politics has also been infesting, and often ruining, many of my other passions, especially Hollywood and the music industry. In other words, this is not explicitly a political blog, but do not be surprised if many of the articles have overlapping categories.
              </p>
              <p className="indent-10" >I am also a big fan of reading. Perhaps the benefit of creating this blog I was most looking forward to was writing book reviews. While I still love a good novel, most of my reading is geared toward journalistic and scholarly nonfiction, preferably, but not always, politically neutral. I love to read not only for the simplistic goal of learning for its own sake, but more importantly, to apply that knowledge to the world around me. How could this or that author's thesis be applied to the libertarian movement? To the Party's goals? It's also important that we all continuously challenge our beliefs and stay open-minded.
              </p>
              <p className="indent-10">To be clear, other subjects will rarely ever touch on politics. Musically, I have unique tastes that are very poorly covered in the US, although I do love all genres. Almost everyone says that, but I'm seriously not kidding. In one trip across town, I jump between the likes of Miley Cyrus (girly pop music), Frank Sinatra (swing), B.O.B (rap), Wisin y Yandel (Spanish reggaeton), Keith Urban (country), and FFDP (hard rock/metal). However, I have a special place in my heart for several obscure subgenres of metal, particularly power and symphonic metal. Power and symphonic metal are not very mainstream even within the US metal community, which itself is not a mainstream genre.  Personally, I believe the reason for that is a lack of classical music in standard education, but I digress. I hope in some small way to maybe change that and spread its awesomeness.
              </p>
              <p className="indent-10">Men's lifestyle is another such subject. Intuitively, this topic has always fascinated me. Growing up, I was anti-social, awkward, sheltered, and shy. My parents were much older than normal and anti-social themselves. The school and church I went to were small (I graduated in a class of 7...yeah 7). I had high aspirations in life and cared deeply about my leadership skills, but when I went to college at 15 years old, I was in for a shock. I had a hard time socializing, working in groups, interacting with others, getting girlfriends, etc. While I couldn't put a name to it at the time, I eventually overcame my shortcomings and gained confidence in myself. After all, it has always been a priority for me to be the best man I can be. At one point, after a particularly rough breakup, I discovered Alpha M and a few other influencers who provided perspective on my own experiences and discover a whole new field of interest.
              </p>
              <p className="indent-10">Last but not least, as a software developer, I am intrigued and passionate about technology issues and trends. Most recently, I've been working with the MERN stack (MongoDB, Express, React, Node.js). As of writing this, I've been learning GraphQL, Gatsby, and Next.js. I started out a couple years ago by learning Java and Android. In this industry, new software is constantly being developed and released that need to be evaluated. Developers never stop learning, which is one of the best things I love about this field. Moreover, new hardware and social trends chronically demand more of developers. AR/VR, electrical vehicles and smart TV's, Starlink, the "Internet of Things", Twitch, to name just a few, require new and better software and constantly change the game. 
              </p>
              <p className="indent-10">
                Hopefully, this page has provided a little context where some may be missing in the articles posted. If anyone has any comments or questions, feel free to use the contact form at the bottom of every page.
              </p>
            </p>
        </div>
    </div>
  );
}
